#!/usr/bin/env bash
# =============================================================================
# adopt-supabase-migrations.sh — move this repo onto the STANDARD Supabase
# migration workflow (supabase/migrations/ + supabase_migrations.schema_migrations),
# baselining the existing production database instead of replaying history.
#
#   ./scripts/adopt-supabase-migrations.sh plan    # default. Prints everything, writes NOTHING.
#   ./scripts/adopt-supabase-migrations.sh write   # writes supabase/migrations/ + a repair script
#
# NEITHER MODE TOUCHES PRODUCTION. `write` only creates local files. The commands
# that touch production are printed for a human to review and run.
#
# ORDER MATTERS AND IS NOT OPTIONAL
#   The historical migrations MUST be marked as already-applied (`migration repair`)
#   BEFORE anyone runs `supabase db push`. If the files exist in supabase/migrations/
#   while the ledger is empty, `db push` would REPLAY ALL 45 FILES against the live
#   database. At least one of them (2026-07-07_catchup_reconcile.sql) embeds a whole
#   historical copy of schema.sql and would REVERT functions that later migrations
#   replaced. That is a production-breaking outcome. This script therefore emits the
#   repair commands first and refuses to run `db push` itself, ever.
# =============================================================================
set -euo pipefail
MODE="${1:-plan}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/migrations"
DEST="$ROOT/supabase/migrations"
REPAIR="$ROOT/scripts/.baseline-repair.sh"

[[ "$MODE" == "plan" || "$MODE" == "write" ]] || { echo "usage: $0 [plan|write]"; exit 2; }

mapfile -t FILES < <(cd "$SRC" && ls -1 *.sql 2>/dev/null | sort)
(( ${#FILES[@]} )) || { echo "no .sql files in $SRC"; exit 2; }

echo "Source      : migrations/            (${#FILES[@]} files, filename order)"
echo "Destination : supabase/migrations/   (Supabase CLI format <14-digit>_name.sql)"
echo "Mode        : $MODE"
echo
[[ "$MODE" == "write" ]] && mkdir -p "$DEST"

declare -A SEQ
VERSIONS=()
for f in "${FILES[@]}"; do
  date_part="${f%%_*}"; rest="${f#*_}"; name="${rest%.sql}"
  compact="${date_part//-/}"
  [[ "$compact" =~ ^[0-9]{8}$ ]] || { echo "SKIP (unparseable date): $f"; continue; }
  n=$(( ${SEQ[$compact]:-0} + 1 )); SEQ[$compact]=$n
  version="${compact}$(printf '%06d' "$n")"
  safe_name="$(echo "$name" | tr -cd '[:alnum:]_' )"
  target="${version}_${safe_name}.sql"
  VERSIONS+=("$version")
  printf '  %-58s -> %s\n' "$f" "$target"
  [[ "$MODE" == "write" ]] && cp "$SRC/$f" "$DEST/$target"
done

if [[ "$MODE" == "write" ]]; then
  {
    echo '#!/usr/bin/env bash'
    echo '# GENERATED by scripts/adopt-supabase-migrations.sh — review before running.'
    echo '# Marks every historical migration as ALREADY APPLIED. `migration repair` only'
    echo '# writes a ledger row; it does NOT execute any SQL against your database.'
    echo 'set -euo pipefail'
    echo 'command -v supabase >/dev/null || { echo "install the Supabase CLI first"; exit 1; }'
    for v in "${VERSIONS[@]}"; do echo "supabase migration repair --status applied $v"; done
    echo 'echo; echo "Baseline complete. Verify with: supabase migration list"'
  } > "$REPAIR"
  chmod +x "$REPAIR"
  echo
  echo "WROTE: supabase/migrations/ (${#VERSIONS[@]} files) and scripts/.baseline-repair.sh"
fi

cat <<BANNER

-------------------------------------------------------------------------------
RUN THESE, IN THIS ORDER, ONCE YOU HAVE REVIEWED THE MAPPING ABOVE
-------------------------------------------------------------------------------
 1.  BACK UP FIRST.  Supabase dashboard -> Database -> Backups -> take a manual
     backup, and confirm it completed. Everything below is reversible only from
     a backup.

 2.  supabase login
     supabase link --project-ref nchtmeqsjkpcvtuscxfy

 3.  Baseline the ledger WITHOUT executing any SQL:
       ./scripts/.baseline-repair.sh
     Confirm every row now reads "Applied":
       supabase migration list

 4.  ONLY AFTER step 3 shows a fully populated ledger, confirm the repo and
     production agree on what is outstanding:
       supabase db diff --linked --schema public

 5.  From this point on, new schema changes are:
       supabase migration new <name>      # creates supabase/migrations/<ts>_<name>.sql
       supabase db push                   # applies ONLY un-applied migrations

DO NOT RUN `supabase db push` BEFORE STEP 3 COMPLETES. With an empty ledger it
would replay all ${#VERSIONS[@]} historical files against the live database.
-------------------------------------------------------------------------------
BANNER
